### PR TITLE
importlib_metadata: define protocol for Distribution.metadata

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@riseup.net>

### CODE REVIEW

**Comment by FFY00** [comment]
Resolves #126.

**Comment by FFY00** [comment]
We run into the case here where we have different coverage in different versions, because of the backport import that will only run on older Python. The proper solution would be to run tests for both versions and merge the coverage, but since it is just an import, I added a `# pragma: no cover` there.

**Comment by FFY00** [comment]
Btw, relevant typeshed definitions: https://github.com/python/typeshed/blob/master/stdlib/3/email/message.pyi

**Comment by jaraco** [comment]
This looks great. I'll add a changelog entry and get it out. Thanks!

**Comment by jaraco** [comment]
Well drat. I renamed the default branch from `master` to `main` and now diffcov is failing again as it was in #257, despite the fix still being applied. It seems the name 'master' is cached or hard-coded in diff-cover.

**Comment by jaraco** [comment]
I'm going to proceed with manually merging and ignore the diff-cover failure for now. If the issue persists in new PRs, I'll probably just get rid of that footgun.

**Pull request merged**
